lang.en={
    "servers": "Servers",
    "settings": "Settings",
    "quit": "Quit",
    "internet": "Internet",
    "favorites": "Favorites",
    "history": "History",
    "direct_connect": "Direct Connect",
    "refresh_list": "Refresh List",
    "filter_hostname": "Filter Hostname",
    "hide_empty": "Hide Empty",
    "hide_full": "Hide Full",
    "hide_password": "Hide Password",
    "hostname": "Hostname",
    "gamemode": "Gamemode",
    "players": "Players",
    "ping": "Ping",
    "ip_address": "IP-Address",
    "password": "Password",
    "example": "Example",
    "leave_empty_not_required": "Leave empty if not required",
    "connect": "Connect",
    "on": "On",
    "off": "Off",
    "low": "Low",
    "medium": "Medium",
    "high": "High",
    "voice_activation": "Voice Activation",
    "push_to_talk": "Push To Talk",
    "epic": "Epic",
    "epic_squared": "Epic²",
    "save": "Save",
    "reset": "Reset",
    "game": "Game",
    "video": "Video",
    "controls": "Controls",
    "apply_and_save": "Apply and Save",
    "show_fps": "Show FPS",
    "limit_fps": "Limit FPS",
    "audio_volume": "Audio Volume",
    "audio_quality": "Audio Quality",
    "mouse_sensitivity": "Mouse Sensitivity",
    "voice_capture": "Voice Capture",
    "voice_threshold": "Voice Threshold",
    "resolution": "Resolution",
    "hdr_output": "HDR Output",
    "anti_aliasing": "Anti Aliasing",
    "shadow_quality": "Shadow Quality",
    "post_process": "Post Process",
    "view_distance": "View Distance",
    "foliage_density": "Foliage Density",
    "texture_quality": "Texture Quality",
    "visual_effects": "Visual Effects",
    "ambient_occlusion": "Ambient Occlusion",
    "no_hdr_support": "Your monitor does not support HDR",
    "fullscreen": "Fullscreen",
    "windowed_fullscreen": "Windowed Fullscreen",
    "windowed": "Windowed",
    "jump": "Jump",
    "walk": "Walk",
    "sprint": "Sprint",
    "crouch": "Crouch",
    "open_close_parachute": "Open/Close Parachute",
    "pointing": "Pointing",
    "reload": "Reload",
    "aim": "Aim",
    "shoot": "Shoot",
    "next_weapon": "Next Weapon",
    "previous_weapon": "Previous Weapon",
    "weapon_menu": "Weapon Menu",
    "disconnect": "Disconnect",
    "continue": "Continue",
    "open_chat": "Open Chat",
    "vehicle_interaction": "Vehicle Interaction",
    "vehicle_horn": "Vehicle Horn",
    "vehicle_nitro": "Vehicle Nitro",
    "door_interaction": "Door Interaction",
    "vehicle_light": "Vehicle Light",
    "vehicle_handbrake": "Vehicle Handbreak",
    "helicopter_up": "Helicopter Up",
    "helicopter_down": "Helicopter Down",
    "helicopter_turn_right": "Helicopter Turn Right",
    "helicopter_turn_left": "Helicopter Turn Left",
    "direct_connect_info": "Directly connect to a server with an IP-Address or domain hostname.",
    "press_any_key_for": "Press any key for:",
    "cancel": "Cancel",
    "key_not_supported": "Input key is not supported for that control setting.",
    "enter_valid_ip": "Please enter a valid server address.",
    "server_asks_password": "Server asks for a password:",
    "join": "Join",
    "incompatible_server": "You can only connect to servers with the same compatibility number.",
    "you_are_playing_on": "You are playing on:",
    "language": "Language",
    "forward": "Move Forward",
    "backward": "Move Backward",
    "move_left": "Move Left",
    "move_right": "Move Right",
    "vehicle_throttle": "Vehicle Throttle",
    "vehicle_brake": "Vehicle Brake",
    "invert_mouse_y": "Invert Mouse Y Axis",
    "mute_menu_music": "Mute Menu Music",
    "audio_volume_vehicles": "Audio Volume Vehicles",
    "audio_volume_weapons": "Audio Volume Weapons",
    "voip_volume": "VoIP Volume",
    "whitelist_explanation": "The server would like to whitelist the following internet domains. If you allow this, the server will be able to initiate HTTP requests from your computer to them.",
    "yes": "Yes",
    "select_all": "Select All",
    "deselect_all": "Deselect All",
    "allow": "Allow",
    "game_folders": "Gamedata Folders",
    "open_cache_folder": "Open Server Cache Folder"
}