lang.fr={
    "servers": "Serveurs",
    "settings": "Options",
    "quit": "Quitter",
    "internet": "Internet",
    "favorites": "Favoris",
    "history": "Historique",
    "direct_connect": "Connexion",
    "refresh_list": "Rafraîchir",
    "filter_hostname": "Filtre Nom de domaine",
    "hide_empty": "Cacher vide",
    "hide_full": "Cacher Plein",
    "hide_password": "Cacher mot de passe",
    "hostname": "Nom de domaine",
    "gamemode": "Mode de jeu",
    "players": "Joueurs",
    "ping": "Latence",
    "ip_address": "Adresse IP",
    "password": "Mot de passe",
    "example": "Exemple",
    "leave_empty_not_required": "Laisser vide si ce n'est pas requis",
    "connect": "Connexion",
    "on": "Oui",
    "off": "Non",
    "low": "Faible",
    "medium": "Moyen",
    "high": "Fort",
    "voice_activation": "Activation à la voix",
    "push_to_talk": "Appuyer pour parler",
    "epic": "Epic",
    "epic_squared": "Ultra",
    "save": "Sauvegarder",
    "reset": "Par défaut",
    "game": "Jeu",
    "video": "Vidéo",
    "controls": "Touches",
    "apply_and_save": "Appliquer et sauvegarder",
    "show_fps": "Afficher les FPS",
    "limit_fps": "Limiter les FPS",
    "audio_volume": "Volume Audio",
    "audio_quality": "Qualité Audio",
    "mouse_sensitivity": "Sensibilité de la souris",
    "voice_capture": "Capture de voix",
    "voice_threshold": "Seuil de voix",
    "resolution": "Résolution",
    "hdr_output": "Sortie HDR",
    "anti_aliasing": "Anti Aliasing",
    "shadow_quality": "Qualité des ombres",
    "post_process": "Post Process",
    "view_distance": "Distance de vue",
    "foliage_density": "Densité du feuillage",
    "texture_quality": "Qualité des textures",
    "visual_effects": "Effets Visuel",
    "ambient_occlusion": "Occlusion ambiante",
    "no_hdr_support": "Votre écran ne supporte pas l'HDR",
    "fullscreen": "Plein écran",
    "windowed_fullscreen": "Plein écran fenêtré",
    "windowed": "Fenêtré",
    "jump": "Sauter",
    "walk": "Marcher",
    "sprint": "Courir",
    "crouch": "S'accroupir",
    "open_close_parachute": "Ouvrir/Fermer le parachute",
    "pointing": "Pointer du doigt",
    "reload": "Recharger",
    "aim": "Viser",
    "shoot": "Tirer",
    "next_weapon": "Arme suivante",
    "previous_weapon": "Arme précédente",
    "weapon_menu": "Menu des armes",
    "disconnect": "Déconnecter",
    "continue": "Continuer",
    "open_chat": "Ouvrir le Chat",
    "vehicle_interaction": "Interaction véhicule",
    "vehicle_horn": "Klaxon du véhicule",
    "vehicle_nitro": "Nitro du véhicule",
    "door_interaction": "Interaction portes",
    "vehicle_light": "Lumière du véhicule",
    "vehicle_handbrake": "Frein à main du véhicule",
    "helicopter_up": "Prendre de l'altitude (Hélicoptère) ",
    "helicopter_down": "Baisser l'altitude (Hélicoptère) ",
    "helicopter_turn_right": "Tourner à droite (Hélicoptère)",
    "helicopter_turn_left": "Tourner à gauche (Hélicoptère)",
    "direct_connect_info": "Connexion directe avec une adresse IP ou nom de domaine",
    "press_any_key_for": "Appuyez sur n'importe quelle touche pour:",
    "cancel": "Annuler",
    "key_not_supported": "La touche entrée n'est pas supportée pour ce paramètre",
    "enter_valid_ip": "Merci d'entrer une adresse de serveur valide",
    "server_asks_password": "Le serveur demande un mot de passe:",
    "join": "Rejoindre",
    "incompatible_server": "Vous pouvez seulement jouer sur le serveur ayant la même version.",
    "you_are_playing_on": "Vous jouez sur",
    "language": "Langage",
    "forward": "Avancer",
    "backward": "Reculer",
    "move_left": "Aller à gauche",
    "move_right": "Aller à droite",
    "vehicle_throttle": "Accélérer",
    "vehicle_brake": "Freiner",
    "invert_mouse_y": "Inverser l'axe Y de la souris",
    "mute_menu_music": "Couper la musique du menu",
    "audio_volume_vehicles": "Volume du son des véhicules",
    "audio_volume_weapons": "Volume du son des armes",
    "voip_volume": "VoIP Volume",
    "whitelist_explanation": "Le serveur voudrait autoriser les sites internet suivants. Si vous les autorisez, le serveur pourra effectuer des requêtes depuis votre ordinateur a ces sites.",
    "yes": "Oui",
    "select_all": "Tout sélectionner",
    "deselect_all": "Désélectionner tout",
    "allow": "Autoriser",
    "game_folders": "Dossiers des données du jeu",
    "open_cache_folder": "Ouvrir le dossier du cache du serveur"
}