lang.hu={
    "servers": "Szerverek",
    "settings": "Beállítások",
    "quit": "Kilépés",
    "internet": "Internet",
    "favorites": "Kevencek",
    "history": "Előzmények",
    "direct_connect": "Direkt csatlakozás",
    "refresh_list": "Lista frissítése",
    "filter_hostname": "Szűrje a gépnévet",
    "hide_empty": "Üres elrejtés",
    "hide_full": "Megtelt elrejtése",
    "hide_password": "Jelszó elrejtése",
    "hostname": "Gépnév",
    "gamemode": "Játékmód",
    "players": "Játékosok",
    "ping": "Ping",
    "ip_address": "IP cím",
    "password": "Jelszó",
    "example": "Példa",
    "leave_empty_not_required": "Ha nem szükséges hadja üresen",
    "connect": "Csatlakozás",
    "on": "Be",
    "off": "Ki",
    "low": "Alacsony",
    "medium": "Közepse",
    "high": "Magas",
    "voice_activation": "Hangaktiválás",
    "push_to_talk": "Push To Talk",
    "epic": "Epik",
    "epic_squared": "Epik²",
    "save": "Mentés",
    "reset": "Visszalállítás",
    "game": "Játék",
    "video": "Videó",
    "controls": "Irányítás",
    "apply_and_save": "Alkalmaz és Mentés",
    "show_fps": "FPS mutatása",
    "limit_fps": "FPS limitálása",
    "audio_volume": "Hangerő",
    "audio_quality": "Hang minősége",
    "mouse_sensitivity": "Egér érzékenység",
    "voice_capture": "Hangrögzítés",
    "voice_threshold": "Hangküszöb",
    "resolution": "Felbontás",
    "hdr_output": "HDR kimenet",
    "anti_aliasing": "Anti Aliasing",
    "shadow_quality": "Árnyék minősége",
    "post_process": "Post Process",
    "view_distance": "Látó távolság",
    "foliage_density": "Lombsűrűség",
    "texture_quality": "Textúra minősége",
    "visual_effects": "Vizuális effektek",
    "ambient_occlusion": "Környezeti elzáródás",
    "no_hdr_support": "A monitor nem támogatja a HDR-t",
    "fullscreen": "Teljes képernyő",
    "windowed_fullscreen": "Ablakos teljes képernyő",
    "windowed": "Ablakos",
    "jump": "Ugrás",
    "walk": "Séta",
    "sprint": "Futás",
    "crouch": "Guggolás",
    "open_close_parachute": "Ejtőernyő nyitása/bezárása",
    "pointing": "Mutatás",
    "reload": "Újra töltés",
    "aim": "Célzás",
    "shoot": "Lövés",
    "next_weapon": "Következő fegyver",
    "previous_weapon": "Előző fegyver",
    "weapon_menu": "Fegyver menü",
    "disconnect": "Kapcsolat bontása",
    "continue": "Folytatás",
    "open_chat": "Csevegés megynyitása",
    "vehicle_interaction": "Jármű Interakció",
    "vehicle_horn": "Jármű duda",
    "vehicle_nitro": "Jármű nitró",
    "door_interaction": "Ajtó Interakció",
    "vehicle_light": "Jármű világítás",
    "vehicle_handbrake": "Jármű kézifék",
    "helicopter_up": "Helikopter fel",
    "helicopter_down": "Helikopter le",
    "helicopter_turn_right": "Helikopter jobbra",
    "helicopter_turn_left": "Helikopter balra",
    "direct_connect_info": "Közvetlenül csatlakozás IP-címmel vagy tartománynévvel.",
    "press_any_key_for": "Nyomja meg bármelyik billentyűt:",
    "cancel": "Megszüntet",
    "key_not_supported": "A bemeneti kulcs nem támogatott az adott vezérlőbeállításhoz.",
    "enter_valid_ip": "Kérjük, adjon meg egy érvényes szerver címet.",
    "server_asks_password": "A szerver jelszót kér:",
    "join": "Csatlakozik",
    "incompatible_server": "Csak azonos kompatibilitási számmal rendelkező szerverekhez csatlakozhatsz.",
    "you_are_playing_on": "Amin játszol:",
    "language": "Nyelv",
    "forward": "Menj tovább",
    "backward": "Menj visszább",
    "move_left": "Menj balra",
    "move_right": "Menj jobbra",
    "vehicle_throttle": "Jármű fojtószelep",
    "vehicle_brake": "Jármű fék",
    "invert_mouse_y": "Egér Y tengely meg fordítsa",
    "mute_menu_music": "Menü zene némítása",
    "audio_volume_vehicles": "Jűrmek hangereje",
    "audio_volume_weapons": "Fegyverek hangereje",
    "voip_volume": "VoIP Hangerő",
    "whitelist_explanation": "A szerver a következő internetes domaineket szeretné engedélyezőlistára tenni. Ha ezt engedélyezi, a szerver képes lesz HTTP-kéréseket kezdeményezni a számítógépről számukra.",
    "yes": "Igen",
    "select_all": "Mindet kiválaszt",
    "deselect_all": "Törölje az összes kijelölését",
    "allow": "Engedélyez",
    "game_folders": "Játék mappa",
    "open_cache_folder": "Szerver gyorsítótár megynitása"
}
