lang.no={
    "servers": "Servere",
    "settings": "Instillinger",
    "quit": "Avslutt",
    "internet": "Internett",
    "favorites": "Favoritter",
    "history": "Historie",
    "direct_connect": "Direkte Tilkobling",
    "refresh_list": "Oppdater Liste",
    "filter_hostname": "Filtrer Vertsnavn",
    "hide_empty": "Skjul Tom",
    "hide_full": "Skjul Full",
    "hide_password": "Skjul Passord",
    "hostname": "Vertsnavn",
    "gamemode": "Spillemodus",
    "players": "Spillere",
    "ping": "Ping",
    "ip_address": "IP-Addresse",
    "password": "Passord",
    "example": "Eksempel",
    "leave_empty_not_required": "La Stå Tom Hvis Ikke Nødvendig",
    "connect": "Tilkobling",
    "on": "På",
    "off": "Av",
    "low": "Lav",
    "medium": "Medium",
    "high": "Høy",
    "voice_activation": "Stemme Aktivering",
    "push_to_talk": "Trykk For Å Snakke",
    "epic": "Episk",
    "epic_squared": "Episk²",
    "save": "Lagre",
    "reset": "Nullstille",
    "game": "Spill",
    "video": "Video",
    "controls": "Kontroller",
    "apply_and_save": "Bruk Og Lagre",
    "show_fps": "Vis FPS",
    "limit_fps": "Begrens FPS",
    "audio_volume": "Lyd Volum",
    "audio_quality": "Lyd Kvalitet",
    "mouse_sensitivity": "Mus Sensitivitet",
    "voice_capture": "Stemme Opptak",
    "voice_threshold": "Stemme Terskel",
    "resolution": "Oppløsning",
    "hdr_output": "HDR Utgang",
    "anti_aliasing": "Anti Aliasing",
    "shadow_quality": "Skygge Kvalitet",
    "post_process": "Innleggsbehandling",
    "view_distance": "Se Avstand",
    "foliage_density": "Løvverkstetthet",
    "texture_quality": "Tekstur Kvalitet",
    "visual_effects": "Visuell Effekt",
    "ambient_occlusion": "Omgivende Okklusjon",
    "no_hdr_support": "Din Skjerm Støtter Ikke HDR",
    "fullscreen": "Fullskjerm",
    "windowed_fullscreen": "Vinduet Fullskjerm",
    "windowed": "Vinduet",
    "jump": "Hopp",
    "walk": "Gå",
    "sprint": "Løp",
    "crouch": "Dukk",
    "open_close_parachute": "Åpne/Lukke Fallskjerm",
    "pointing": "Peke",
    "reload": "lade",
    "aim": "Sikte",
    "shoot": "Skyte",
    "next_weapon": "Neste Våpen",
    "previous_weapon": "Forrige Våpen",
    "weapon_menu": "Våpen Meny",
    "disconnect": "Koble Fra",
    "continue": "Fortsett",
    "open_chat": "Åpne Chat",
    "vehicle_interaction": "Kjøretøy Interaksjon",
    "vehicle_horn": "Kjøretøy Horn",
    "vehicle_nitro": "Kjøretøy Nitro",
    "door_interaction": "Dør Interaksjon",
    "vehicle_light": "Kjøretøy Lys",
    "vehicle_handbrake": "Kjøretøy Håndbrekk",
    "helicopter_up": "Helikopter Opp",
    "helicopter_down": "Helikopter Ned",
    "helicopter_turn_right": "Helikopter Sving Høyre",
    "helicopter_turn_left": "Helikopter Sving Venstre",
    "direct_connect_info": "Koble Direkte Til IP-Addresse Eller Vertsnavn.",
    "press_any_key_for": "Trykk På Hvilken Som Helst Tast For:",
    "cancel": "Avbryt",
    "key_not_supported": "Denne Knappen Støtter Ikke Denne Funksjonen.",
    "enter_valid_ip": "Skriv Inn En Gyldig Server Addresse.",
    "server_asks_password": "Server Spør Etter Passord:",
    "join": "Bli Med",
    "incompatible_server": "Du Kan Bare Koble Til Servere Med Samme Kompatibel Nummer.",
    "you_are_playing_on": "Du Spiller På:",
    "language": "Språk",
    "forward": "Gå Forrover",
    "backward": "Gå Bakover",
    "move_left": "Gå Venstre",
    "move_right": "Gå Høyre",
    "vehicle_throttle": "Kjøretøy Gasspedal",
    "vehicle_brake": "Kjøretøy Brems",
    "invert_mouse_y": "Inverter Mus Y Akse",
    "mute_menu_music": "Demp Musikk Meny",
    "audio_volume_vehicles": "Lyd Volum Kjøretøy",
    "audio_volume_weapons": "Lyd Volum Våpen",
    "voip_volume": "VoIP Volum",
    "whitelist_explanation": "Serveren Vil Hvitliste Følgende Internettdomener. Hvis Du Tillater Dette, Vil Serveren Kunne Starte HTTP-Forespørsler Fra Datamaskinen Din Til Dem.",
    "yes": "Ja",
    "select_all": "Marker Alle",
    "deselect_all": "Fjern Markering Alle",
    "allow": "Tillate",
    "game_folders": "Spilldata Mappe",
    "open_cache_folder": "Åpne Server Cache Mappe"
}
