lang.ru={
    "servers": "Сервера",
    "settings": "Настройки",
    "quit": "Выйти",
    "internet": "Интернет",
    "favorites": "Избранные",
    "history": "История",
    "direct_connect": "Прямое",
    "refresh_list": "Обновить",
    "filter_hostname": "Фильтр названий серверов",
    "hide_empty": "Скрыть пустые",
    "hide_full": "Скрыть полные",
    "hide_password": "Скрыть с паролем",
    "hostname": "Название",
    "gamemode": "Режим",
    "players": "Игроки",
    "ping": "Пинг",
    "ip_address": "Айпи адрес",
    "password": "Пароль",
    "example": "Пример",
    "leave_empty_not_required": "Оставьте пустым, если сервер без пароля",
    "connect": "Подключиться",
    "on": "Вкл",
    "off": "Выкл",
    "low": "Низкие",
    "medium": "Средние",
    "high": "Высокие",
    "voice_activation": "Активация микрофона",
    "push_to_talk": "Нажать и говорить",
    "epic": "Эпик",
    "epic_squared": "Ультра",
    "save": "Сохранить",
    "reset": "Сбросить",
    "game": "Игра",
    "video": "Видео",
    "controls": "Управление",
    "apply_and_save": "Применить и сохранить",
    "show_fps": "Показать ФПС",
    "limit_fps": "Ограничение ФПС",
    "audio_volume": "Громкость звука",
    "audio_quality": "Качество звука",
    "mouse_sensitivity": "Чувствительность мыши",
    "voice_capture": "Захват голоса",
    "voice_threshold": "Чувствительность микрофона",
    "resolution": "Разрешение",
    "hdr_output": "HDR Выход",
    "anti_aliasing": "Сглаживание",
    "shadow_quality": "Качество теней",
    "post_process": "Постобработка",
    "view_distance": "Дальность прорисовки",
    "foliage_density": "Плотность растительности",
    "texture_quality": "Качество текстур",
    "visual_effects": "Визуальные эффекты",
    "ambient_occlusion": "Затенения объектов",
    "no_hdr_support": "Ваш монитор не поддерживает HDR",
    "fullscreen": "Полный экран",
    "windowed_fullscreen": "Оконный режим во весь экран",
    "windowed": "Оконный",
    "jump": "Прыжок",
    "walk": "Ходьба",
    "sprint": "Бег",
    "crouch": "Красться",
    "open_close_parachute": "Открыть / закрыть парашют",
    "pointing": "Показывать",
    "reload": "Перезарядка",
    "aim": "Прицел",
    "shoot": "Выстрел",
    "next_weapon": "Следующее оружие",
    "previous_weapon": "Предыдущие оружие",
    "weapon_menu": "Меню оружия",
    "disconnect": "Отключится",
    "continue": "Продолжить",
    "open_chat": "Открыть чат",
    "vehicle_interaction": "Взаимодействие с транспортом",
    "vehicle_horn": "Звуковой сигнал транспорта",
    "vehicle_nitro": "Нитро ускорение транспорта",
    "door_interaction": "Взаимодействие с дверью",
    "vehicle_light": "Фары транспорта",
    "vehicle_handbrake": "Ручник транспорта",
    "helicopter_up": "Набрать высоту на вертолёте",
    "helicopter_down": "Снизить высоту на вертолёте",
    "helicopter_turn_right": "Поворот вертолёта направо",
    "helicopter_turn_left": "Поворот вертолёта налево",
    "direct_connect_info": "Прямое подключение к серверу с IP-адресом или доменным именем хоста.",
    "press_any_key_for": "Нажмите любую клавишу для:",
    "cancel": "Отмена",
    "key_not_supported": "Клавиша ввода не поддерживается для этого параметра управления.",
    "enter_valid_ip": "Пожалуйста, введите правильный адрес сервера.",
    "server_asks_password": "Сервер запрашивает пароль:",
    "join": "Присоединиться",
    "incompatible_server": "Вы можете подключиться только к серверам с одинаковой версией игры.",
    "you_are_playing_on": "Вы играете на:",
    "language": "Язык",
    "forward": "Идти вперёд ",
    "backward": "Идти назад",
    "move_left": "Идти влево",
    "move_right": "Идти вправо",
    "vehicle_throttle": "ускорять",
    "vehicle_brake": "замедляются",
    "invert_mouse_y": "Инвертировать мышь по оси Y",
    "mute_menu_music": "Выключить музыку в меню",
    "audio_volume_vehicles": "Audio Volume Vehicles",
    "audio_volume_weapons": "Audio Volume Weapons",
    "voip_volume": "VoIP Громкость звука",
    "whitelist_explanation": "Сервер хотел бы включить в белый список следующие интернет-домены. Если вы разрешите это, сервер сможет инициировать HTTP-запросы с вашего компьютера к ним.",
    "yes": "Да",
    "select_all": "Выберите все",
    "deselect_all": "Удалить все",
    "allow": "Разрешить",
    "game_folders": "Папки Гамедата",
    "open_cache_folder": "Папка открытого кэша сервера"
}