lang.tr={
    "servers": "Sunucular",
    "settings": "Ayarlar",
    "quit": "Çık",
    "internet": "İnternet",
    "favorites": "Favoriler",
    "history": "Geçmiş",
    "direct_connect": "Doğrudan Bağlan",
    "refresh_list": "Listeyi Yenile",
    "filter_hostname": "Sunucu Adı Filtresi",
    "hide_empty": "Boşları Gizle",
    "hide_full": "Doluları Gizle",
    "hide_password": "Şifrelileri Gizle",
    "hostname": "Sunucu Adı",
    "gamemode": "Oyun Modu",
    "players": "Oyuncular",
    "ping": "Ping",
    "ip_address": "IP Adresi",
    "password": "Şifre",
    "example": "Örnek",
    "leave_empty_not_required": "Gerekmiyorsa Boş Bırak",
    "connect": "Bağlan",
    "on": "Açık",
    "off": "Kapalı",
    "low": "Düşük",
    "medium": "Orta",
    "high": "Yüksek",
    "voice_activation": "Ses Etkinliği",
    "push_to_talk": "Bas Konuş",
    "epic": "Epik",
    "epic_squared": "Ultra",
    "save": "Kaydet",
    "reset": "Sıfırla",
    "game": "Oyun",
    "video": "Video",
    "controls": "Kontroller",
    "apply_and_save": "Uygula ve Kaydet",
    "show_fps": "FPS Göster",
    "limit_fps": "FPS Sabitleme",
    "audio_volume": "Ses Seviyesi",
    "audio_quality": "Ses Kalitesi",
    "mouse_sensitivity": "Fare Hassasiyeti",
    "voice_capture": "Ses Yakalama",
    "voice_threshold": "Ses Hassasiyeti",
    "resolution": "Çözünürlük",
    "hdr_output": "HDR Çıkışı",
    "anti_aliasing": "Kenar Yumuşatma",
    "shadow_quality": "Gölge Kalitesi",
    "post_process": "İşlem Sonrası Detayı",
    "view_distance": "Görüş Mesafesi",
    "foliage_density": "Çimen Yoğunluğu",
    "texture_quality": "Kaplama Kalitesi",
    "visual_effects": "Görsel Efektler",
    "ambient_occlusion": "Ambiyans Detayı",
    "no_hdr_support": "Bu monitör HDR desteklemiyor.",
    "fullscreen": "Tam Ekran",
    "windowed_fullscreen": "Pencereli Tam Ekran",
    "windowed": "Pencere Modu",
    "jump": "Zıpla",
    "walk": "Yürü",
    "sprint": "Koş",
    "crouch": "Eğilme",
    "open_close_parachute": "Paraşüt açma/kapama",
    "pointing": "İşaretleme",
    "reload": "Şarjör Değiştir",
    "aim": "Nişan Al",
    "shoot": "Ateş Et",
    "next_weapon": "Sonraki Silah",
    "previous_weapon": "Önceki Silah",
    "weapon_menu": "Silah Menüsü",
    "disconnect": "Bağlantıyı Kes",
    "continue": "Devam et",
    "open_chat": "Sohbeti Aç",
    "vehicle_interaction": "Araba Etkileşimi",
    "vehicle_horn": "Korna",
    "vehicle_nitro": "Araç Nitrosu",
    "door_interaction": "Kapı Etkileşimi",
    "vehicle_light": "Araç ışıkları",
    "vehicle_handbrake": "El Freni",
    "helicopter_up": "Helikopter Yükseltme",
    "helicopter_down": "Helikopter Alçaltma",
    "helicopter_turn_right": "Helikopterle Sağa Dön",
    "helicopter_turn_left": "Helikopterle Sola dön",
    "direct_connect_info": "IP-Adres veya Sunucu adıyla doğrudan bağlan",
    "press_any_key_for": "Herhangi bir tuşa basınız",
    "cancel": "Iptal",
    "key_not_supported": "Atadığınız tuş kombinasyonu uyumlu değil",
    "enter_valid_ip": "Lütfen doğru server adresi giriniz",
    "server_asks_password": "Sunucu şifre talep ediyor",
    "join": "Katıl",
    "incompatible_server": "Yalnızca aynı uyumluluk numarasına sahip sunuculara bağlanabilirsiniz.",
    "you_are_playing_on": "Şu an oynuyorsun:",
    "language": "Diller",
    "forward": "İleri Hareket Et",
    "backward": "Geri Hareket Et",
    "move_left": "Sola Hareket Et",
    "move_right": "Sağa Hareket Et",
    "vehicle_throttle": "Araç Hızlandırma",
    "vehicle_brake": "Araç Freni",
    "invert_mouse_y": "Mouse Y Yönünde Ters Çevir",
    "mute_menu_music": "Menü Müziklerini Sustur",
    "audio_volume_vehicles": "Araç Ses Ayarları",
    "audio_volume_weapons": "Silah Ses Ayarları",
    "voip_volume": "VoIP Ses Seviyesi",
    "whitelist_explanation": "Onaylanmış-liste_açıklanması",
    "yes": "Evet",
    "select_all": "Tümünü seç",
    "deselect_all": "Tümünü kaldır",
    "allow": "Kabul etmek",
    "game_folders": "Gamedata Klasörleri",
    "open_cache_folder": "Sunucu Önbellek Klasörünü Aç"
}